"""Add super_name column to Hero table

Revision ID: 140f3bf22415
Revises: f9e7b21b1960
Create Date: 2023-07-04 12:40:19.443441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '140f3bf22415'
down_revision = 'f9e7b21b1960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero', schema=None) as batch_op:
        batch_op.add_column(sa.Column('super_name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero', schema=None) as batch_op:
        batch_op.drop_column('super_name')

    # ### end Alembic commands ###
