"""Add strength column to HeroPower table

Revision ID: 29b53e561785
Revises: d7e2d22f1a52
Create Date: 2023-07-04 12:05:38.064884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b53e561785'
down_revision = 'd7e2d22f1a52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_power', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strength', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_power', schema=None) as batch_op:
        batch_op.drop_column('strength')

    # ### end Alembic commands ###
