"""Add name column to Power table

Revision ID: 9a50fa920c0f
Revises: 29b53e561785
Create Date: 2023-07-04 12:16:27.476637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a50fa920c0f'
down_revision = '29b53e561785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('power', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('power', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
