"""Add description column to Power table

Revision ID: ee7138087be5
Revises: 9a50fa920c0f
Create Date: 2023-07-04 12:28:53.287235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee7138087be5'
down_revision = '9a50fa920c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('power', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('power', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
