"""Add name column to Hero table

Revision ID: f9e7b21b1960
Revises: ee7138087be5
Create Date: 2023-07-04 12:31:18.245145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e7b21b1960'
down_revision = 'ee7138087be5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
